Resources:
    S3EventQueue:
        Type: 'AWS::SQS::Queue'
        Properties:
            VisibilityTimeout: 20
    S3EventQueuePolicy:
        Type: 'AWS::SQS::QueuePolicy'
        Properties:
            PolicyDocument: {Id: S3-SQS-Policy, Statement: [{Sid: MyQueuePolicy, Effect: Allow, Principal: '*', Action: 'SQS:*', Resource: '*', Condition: {ArnLike: {'aws:SourceArn': 'arn:aws:s3:::*'}}}]}
            Queues:
              - !Ref S3EventQueue
    UploadS3:
        Type: 'AWS::S3::Bucket'
        DependsOn:
            - S3EventQueuePolicy
        Properties:
            NotificationConfiguration: {QueueConfigurations: [{Event: 's3:ObjectCreated:*', Queue: !GetAtt S3EventQueue.Arn}]}
Outputs:
    SQSName:
        Description: 'SQS Name from Ref'
        Value: !GetAtt S3EventQueue.QueueName
